### PR TITLE
Update `syn`, `quote` and `proc-macro2`

### PR DESCRIPTION
**Pull request by hcpl**

### CODE REVIEW

**Comment by nrc** [comment]
Looks like nightly tests are failing. Do you know what is happening there?

**Comment by hcpl** [comment]
This is because each of these commands: https://github.com/nrc/derive-new/blob/f944f104c64cc4104c6c47c0c3baca9363c7f0c3/.travis.yml#L6-L9 creates its own `target/debug/deps/libderive_new-${hash}.so` with a unique hash which confuses `compiletest_rs` since it doesn't know how to tell which one is the right one.

**Comment by nrc** [comment]
Thanks for the PR!

**Comment by hcpl** [comment]
I just tried the script below which resolved this problem for me:
```sh
#!/bin/sh
cargo +nightly test
rm target/debug/deps/libderive_new-*.so
cargo +nightly test --manifest-path testcrate/Cargo.toml
```

I'll try to adapt this for `.travis.yml` in the next PR.

**Pull request merged**
